### PR TITLE
Added Cineplex to git.

### PR DESCRIPTION
**Pull request by finalgega**
Refactored a bunch of variables to make them readable but less short.

Added a testCalculateAge() to User for date calculation example/work for dob/age category (Child/Adult/Senior Citizen)?

Implemented Staff Login, but have not linked staff functions to it yet.

### CODE REVIEW

**Comment by heutzi** [comment]
Did you already modified FileIOController to integrate age into user.txt ?

**Comment by finalgega** [comment]
Not yet, but its possible with adding a user.getAge() and implementing a calculate age part. I didn't finish it yesterday because I was falling asleep, will continue work on it. Currently there's only a testCalculateAge() method in User.java as it was a scratchpad to test if it can work

**Comment by heutzi** [comment]
I think should integrate the part where you are asking a user his age to MainMenu rather than puting it into the User class. If i'm right, entities should not contain any interaction with the application users.

**Comment by heutzi** [comment]
Also I think that the age category should not be a part of the user class considering it may be varying over time : we need to consider that our application may be used for long period. That's why I would rather add the calculus of the age category to the booking function

**Pull request merged**
